# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.roles_api import RolesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_role_count(self):
        """Test case for role_count

        Counts the Roles  # noqa: E501
        """
        pass

    def test_role_create(self):
        """Test case for role_create

        Create a Role  # noqa: E501
        """
        pass

    def test_role_delete(self):
        """Test case for role_delete

        Delete a Role  # noqa: E501
        """
        pass

    def test_role_find(self):
        """Test case for role_find

        Get a Role  # noqa: E501
        """
        pass

    def test_role_permission_count(self):
        """Test case for role_permission_count

        Counts the RolePermissions  # noqa: E501
        """
        pass

    def test_role_permission_create(self):
        """Test case for role_permission_create

        Create a RolePermission  # noqa: E501
        """
        pass

    def test_role_permission_delete(self):
        """Test case for role_permission_delete

        Delete an RolePermission  # noqa: E501
        """
        pass

    def test_role_permission_find(self):
        """Test case for role_permission_find

        Get a RolePermission  # noqa: E501
        """
        pass

    def test_role_permission_query(self):
        """Test case for role_permission_query

        Queries the RolePermissions  # noqa: E501
        """
        pass

    def test_role_permission_simple_query(self):
        """Test case for role_permission_simple_query

        Gets the RolePermission list in the scope  # noqa: E501
        """
        pass

    def test_role_query(self):
        """Test case for role_query

        Queries the Roles  # noqa: E501
        """
        pass

    def test_role_simple_query(self):
        """Test case for role_simple_query

        Gets the Role list in the scope  # noqa: E501
        """
        pass

    def test_role_update(self):
        """Test case for role_update

        Update an Role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
