# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tags_api import TagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tag(self):
        """Test case for create_tag

        Create a Tag  # noqa: E501
        """
        pass

    def test_tag_count(self):
        """Test case for tag_count

        Counts the Tags  # noqa: E501
        """
        pass

    def test_tag_delete(self):
        """Test case for tag_delete

        Delete an Tag  # noqa: E501
        """
        pass

    def test_tag_find(self):
        """Test case for tag_find

        Get a Tag  # noqa: E501
        """
        pass

    def test_tag_query(self):
        """Test case for tag_query

        Queries the Tags  # noqa: E501
        """
        pass

    def test_tag_simple_query(self):
        """Test case for tag_simple_query

        Gets the Tag list in the scope  # noqa: E501
        """
        pass

    def test_tag_update(self):
        """Test case for tag_update

        Update a Tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
