# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_package_uninstall_request import DevicePackageUninstallRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestDevicePackageUninstallRequest(unittest.TestCase):
    """DevicePackageUninstallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevicePackageUninstallRequest(self):
        """Test DevicePackageUninstallRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_package_uninstall_request.DevicePackageUninstallRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
