# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_channels_api import DataChannelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataChannelsApi(unittest.TestCase):
    """DataChannelsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.data_channels_api.DataChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_channel_count(self):
        """Test case for data_channel_count

        Counts the ChannelInfos  # noqa: E501
        """
        pass

    def test_data_channel_find(self):
        """Test case for data_channel_find

        Gets an ChannelInfo  # noqa: E501
        """
        pass

    def test_data_channel_query(self):
        """Test case for data_channel_query

        Queries the ChannelInfos  # noqa: E501
        """
        pass

    def test_data_channel_simple_query(self):
        """Test case for data_channel_simple_query

        Gets the ChannelInfo list in the scope  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
