# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.credential_query import CredentialQuery  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialQuery(unittest.TestCase):
    """CredentialQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialQuery(self):
        """Test CredentialQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.credential_query.CredentialQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
