# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

#from swagger_client.models.account import Account  # noqa: F401,E501
from swagger_client.models.organization import Organization  # noqa: F401,E501


class Account(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'organization': 'Organization',
        'parent_account_path': 'str',
        'child_accounts': 'list[Account]',
        'expiration_date': 'datetime',
        'type': 'str',
        'name': 'str',
        'modified_on': 'datetime',
        'modified_by': 'str',
        'optlock': 'int',
        'entity_attributes': 'dict(str, str)',
        'entity_properties': 'dict(str, str)',
        'scope_id': 'str',
        'id': 'str',
        'created_on': 'datetime',
        'created_by': 'str'
    }

    attribute_map = {
        'organization': 'organization',
        'parent_account_path': 'parentAccountPath',
        'child_accounts': 'childAccounts',
        'expiration_date': 'expirationDate',
        'type': 'type',
        'name': 'name',
        'modified_on': 'modifiedOn',
        'modified_by': 'modifiedBy',
        'optlock': 'optlock',
        'entity_attributes': 'entityAttributes',
        'entity_properties': 'entityProperties',
        'scope_id': 'scopeId',
        'id': 'id',
        'created_on': 'createdOn',
        'created_by': 'createdBy'
    }

    def __init__(self, organization=None, parent_account_path=None, child_accounts=None, expiration_date=None, type=None, name=None, modified_on=None, modified_by=None, optlock=None, entity_attributes=None, entity_properties=None, scope_id=None, id=None, created_on=None, created_by=None):  # noqa: E501
        """Account - a model defined in Swagger"""  # noqa: E501

        self._organization = None
        self._parent_account_path = None
        self._child_accounts = None
        self._expiration_date = None
        self._type = None
        self._name = None
        self._modified_on = None
        self._modified_by = None
        self._optlock = None
        self._entity_attributes = None
        self._entity_properties = None
        self._scope_id = None
        self._id = None
        self._created_on = None
        self._created_by = None
        self.discriminator = None

        if organization is not None:
            self.organization = organization
        if parent_account_path is not None:
            self.parent_account_path = parent_account_path
        if child_accounts is not None:
            self.child_accounts = child_accounts
        if expiration_date is not None:
            self.expiration_date = expiration_date
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if modified_on is not None:
            self.modified_on = modified_on
        if modified_by is not None:
            self.modified_by = modified_by
        if optlock is not None:
            self.optlock = optlock
        if entity_attributes is not None:
            self.entity_attributes = entity_attributes
        if entity_properties is not None:
            self.entity_properties = entity_properties
        if scope_id is not None:
            self.scope_id = scope_id
        if id is not None:
            self.id = id
        if created_on is not None:
            self.created_on = created_on
        if created_by is not None:
            self.created_by = created_by

    @property
    def organization(self):
        """Gets the organization of this Account.  # noqa: E501


        :return: The organization of this Account.  # noqa: E501
        :rtype: Organization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Account.


        :param organization: The organization of this Account.  # noqa: E501
        :type: Organization
        """

        self._organization = organization

    @property
    def parent_account_path(self):
        """Gets the parent_account_path of this Account.  # noqa: E501


        :return: The parent_account_path of this Account.  # noqa: E501
        :rtype: str
        """
        return self._parent_account_path

    @parent_account_path.setter
    def parent_account_path(self, parent_account_path):
        """Sets the parent_account_path of this Account.


        :param parent_account_path: The parent_account_path of this Account.  # noqa: E501
        :type: str
        """

        self._parent_account_path = parent_account_path

    @property
    def child_accounts(self):
        """Gets the child_accounts of this Account.  # noqa: E501


        :return: The child_accounts of this Account.  # noqa: E501
        :rtype: list[Account]
        """
        return self._child_accounts

    @child_accounts.setter
    def child_accounts(self, child_accounts):
        """Sets the child_accounts of this Account.


        :param child_accounts: The child_accounts of this Account.  # noqa: E501
        :type: list[Account]
        """

        self._child_accounts = child_accounts

    @property
    def expiration_date(self):
        """Gets the expiration_date of this Account.  # noqa: E501


        :return: The expiration_date of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this Account.


        :param expiration_date: The expiration_date of this Account.  # noqa: E501
        :type: datetime
        """

        self._expiration_date = expiration_date

    @property
    def type(self):
        """Gets the type of this Account.  # noqa: E501


        :return: The type of this Account.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Account.


        :param type: The type of this Account.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this Account.  # noqa: E501


        :return: The name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Account.


        :param name: The name of this Account.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def modified_on(self):
        """Gets the modified_on of this Account.  # noqa: E501


        :return: The modified_on of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this Account.


        :param modified_on: The modified_on of this Account.  # noqa: E501
        :type: datetime
        """

        self._modified_on = modified_on

    @property
    def modified_by(self):
        """Gets the modified_by of this Account.  # noqa: E501


        :return: The modified_by of this Account.  # noqa: E501
        :rtype: str
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this Account.


        :param modified_by: The modified_by of this Account.  # noqa: E501
        :type: str
        """

        self._modified_by = modified_by

    @property
    def optlock(self):
        """Gets the optlock of this Account.  # noqa: E501


        :return: The optlock of this Account.  # noqa: E501
        :rtype: int
        """
        return self._optlock

    @optlock.setter
    def optlock(self, optlock):
        """Sets the optlock of this Account.


        :param optlock: The optlock of this Account.  # noqa: E501
        :type: int
        """

        self._optlock = optlock

    @property
    def entity_attributes(self):
        """Gets the entity_attributes of this Account.  # noqa: E501


        :return: The entity_attributes of this Account.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._entity_attributes

    @entity_attributes.setter
    def entity_attributes(self, entity_attributes):
        """Sets the entity_attributes of this Account.


        :param entity_attributes: The entity_attributes of this Account.  # noqa: E501
        :type: dict(str, str)
        """

        self._entity_attributes = entity_attributes

    @property
    def entity_properties(self):
        """Gets the entity_properties of this Account.  # noqa: E501


        :return: The entity_properties of this Account.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._entity_properties

    @entity_properties.setter
    def entity_properties(self, entity_properties):
        """Sets the entity_properties of this Account.


        :param entity_properties: The entity_properties of this Account.  # noqa: E501
        :type: dict(str, str)
        """

        self._entity_properties = entity_properties

    @property
    def scope_id(self):
        """Gets the scope_id of this Account.  # noqa: E501


        :return: The scope_id of this Account.  # noqa: E501
        :rtype: str
        """
        return self._scope_id

    @scope_id.setter
    def scope_id(self, scope_id):
        """Sets the scope_id of this Account.


        :param scope_id: The scope_id of this Account.  # noqa: E501
        :type: str
        """

        self._scope_id = scope_id

    @property
    def id(self):
        """Gets the id of this Account.  # noqa: E501


        :return: The id of this Account.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Account.


        :param id: The id of this Account.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created_on(self):
        """Gets the created_on of this Account.  # noqa: E501


        :return: The created_on of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Account.


        :param created_on: The created_on of this Account.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def created_by(self):
        """Gets the created_by of this Account.  # noqa: E501


        :return: The created_by of this Account.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Account.


        :param created_by: The created_by of this Account.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Account, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
