# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.device_component_configuration import DeviceComponentConfiguration  # noqa: F401,E501


class DeviceConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'component_configurations': 'list[DeviceComponentConfiguration]'
    }

    attribute_map = {
        'component_configurations': 'componentConfigurations'
    }

    def __init__(self, component_configurations=None):  # noqa: E501
        """DeviceConfiguration - a model defined in Swagger"""  # noqa: E501

        self._component_configurations = None
        self.discriminator = None

        if component_configurations is not None:
            self.component_configurations = component_configurations

    @property
    def component_configurations(self):
        """Gets the component_configurations of this DeviceConfiguration.  # noqa: E501


        :return: The component_configurations of this DeviceConfiguration.  # noqa: E501
        :rtype: list[DeviceComponentConfiguration]
        """
        return self._component_configurations

    @component_configurations.setter
    def component_configurations(self, component_configurations):
        """Sets the component_configurations of this DeviceConfiguration.


        :param component_configurations: The component_configurations of this DeviceConfiguration.  # noqa: E501
        :type: list[DeviceComponentConfiguration]
        """

        self._component_configurations = component_configurations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
