# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class KapuaDataPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metrics': 'dict(str, object)',
        'body': 'str'
    }

    attribute_map = {
        'metrics': 'metrics',
        'body': 'body'
    }

    def __init__(self, metrics=None, body=None):  # noqa: E501
        """KapuaDataPayload - a model defined in Swagger"""  # noqa: E501

        self._metrics = None
        self._body = None
        self.discriminator = None

        if metrics is not None:
            self.metrics = metrics
        if body is not None:
            self.body = body

    @property
    def metrics(self):
        """Gets the metrics of this KapuaDataPayload.  # noqa: E501


        :return: The metrics of this KapuaDataPayload.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this KapuaDataPayload.


        :param metrics: The metrics of this KapuaDataPayload.  # noqa: E501
        :type: dict(str, object)
        """

        self._metrics = metrics

    @property
    def body(self):
        """Gets the body of this KapuaDataPayload.  # noqa: E501


        :return: The body of this KapuaDataPayload.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this KapuaDataPayload.


        :param body: The body of this KapuaDataPayload.  # noqa: E501
        :type: str
        """

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KapuaDataPayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KapuaDataPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
